---
title: "About Me"
description: |
  Data for education reform..
---

## `Work Experience`

**Researcher and Statistician**, [CivicDataLab](https://civicdatalab.in/)  
`May, '20 - Present`

> Using public finance data to investigate, advocate and advance child education and well being in rural India.


**Core Team Member**, [DataKind](https://datakind.org/)  
`Jul, '18 - Oct, '20`

> Pro bono consulting and community collaboration on social innovation data science projects.

**Data Analyst**, [Pratham Books](https://prathambooks.org/)  
`Jul, '18 - May, '20`

> Analytics strategy and architecture for the organisation’s open source and open content digital platform, [StoryWeaver](https://storyweaver.org.in/).  

**Data Fellow**, [Uptake.org](https://uptake.org/)  
`Mar, '19 - Sep, '19`

> 6-month data science fellowship program to enhance the user retention on Pratham Books' StoryWeaver.

## `Education`

**B.Sc. (H) Statistics**, Sri Venkateswara College, University of Delhi  
`Jul, '11 - May, '14`

## `Engagements`

**Guest Lecturer**, [Srishti Institute of Art, Design and Technology](http://www.srishti.ac.in/)  

> Data driven design and real world applications.

**Data Privacy Primer**  

> Session on the basics of internet privacy, the landscape and individual action.

### [`See Resume`](https://www.dropbox.com/s/c6z6qmybv8zxkcr/arpit_arora_resume_20200726.pdf?dl=0)
